@startmindmap

!include ../style/mind-map-style.iuml

title 刑法总论（简略）

* 刑法总论
    * 刑法论
        * 刑罚的解释
        * 刑罚的基本原则
        * 刑罚的效力
    * 犯罪论<<orange>>
        * 犯罪成立问题
            * 客观要件 → 客观（违法）阻却事由
            * 主观要件 → 主观（责任）阻却事由
        * 犯罪成立之后的问题
            * 犯罪的事件发展问题：犯罪形态（预备 → 中止 → 未遂 → 既遂）
            * 犯罪的空间分布问题：共同犯罪（正犯 → 共犯）
            * 犯罪的数量计算问题：罪数（一罪 → 数罪）
    * 刑罚论
        * 刑罚的体系 → 裁量 → 执行 → 消灭



@endmindmap