@startmindmap

!include ../style/mind-map-style.iuml

title 刑法分论

* 刑法分论
    * 侵犯个人法益
        * 人身犯罪
            * 个人
                * 生命、身体、性权利
                * 自由、名誉、民主权利
            * 家庭
                * 婚姻家庭权利
        * 财产犯罪
            * 侵占罪与盗窃罪
            * 抢夺罪与抢劫罪
            * 敲诈勒索罪与诈骗罪
    * 侵犯社会法益
        * 危害公共安全罪
        * 破坏经济秩序罪
        * 妨害社会管理罪
    * 侵犯国家法益
        * 侵害国家职能的犯罪
            * 贪污贿赂罪
                * 贪污罪、受贿罪、挪用公款罪
            * 渎职罪
        * 危害国家存立的犯罪
            * 危害国家安全罪



@endmindmap