@startmindmap

!include ../style/mind-map-style.iuml

title 结果加重犯（法益视角）

* 结果加重犯（法益视角）
    * 侵犯个人法益
        * 人身犯罪
            * 生命、身体
                * 故意杀人罪<<red>>
                * 故意伤害罪<<green>>
                    * 过失
                * 遗弃罪<<grey>>
                    *_ 不作为犯罪
            * 性权利
                * 强奸罪<<green>>
                * 强制猥亵、侮辱罪<<grey>>
            * 人身自由
                * 非法拘禁罪<<green>>
                    * 过失
                * 拐卖妇女、儿童罪<<green>>
                * 绑架罪
            * 名誉权、人身权
                * 侮辱罪<<grey>>
                * 诽谤罪<<grey>>
            * 婚姻家庭
                * 暴力干涉婚姻自由罪<<green>>
                    * 过失
                * 虐待罪<<green>>
                    * 过失
        * 财产犯罪
            * 抢夺罪（对物暴力，对人有危险）<<green>>
                * 过失
            * 抢劫罪（对人暴力，压制反抗）<<green>>
    * 侵犯社会法益
        * 危害公共安全
            * 放火罪<<green>>


@endmindmap