@startmindmap

!include ../style/mind-map-style.iuml

title 结果加重犯

* 结果加重犯（A+B）
    * 一个行为
        * 基本犯（A罪）
            * 定基本犯（A罪）
        * 加重结果（B罪）
            * B罪成为基本犯（A罪）的法定刑升格条件，加重处罚


@endmindmap