@startmindmap

!include ../style/mind-map-style.iuml

title 法益侵害事实分类

* 法益侵害事实分类
    * 样态
        * 危险状态<<green>>
            *_ 潜在的危害
        * 实害结果<<green>>
            *_ 显现的危害
    * 是否有实害结果
        * 危险犯 = 行为犯<<green>>
            * 抽象危险犯<<green>>
                * 要求
                    * 只需要具备抽象危险
                    * 危险是立法者认定的，不需要法官具体判断
            * 具体危险犯<<green>>
                * 要求
                    * 只需要具备具体危险
                    * 危险需要法官具体判断
        * 实害犯 = 结果犯<<green>>
            * 要求
                * 实害结果


@endmindmap