@startmindmap

!include ../style/mind-map-style.iuml

title 刑法总论（详细）

* 刑法总论
    * 刑法论
        * 刑法的解释
            * 解释技巧
            * 解释理由
        * 刑法的基本原则
            * 罪刑法定
            * 罪刑相适应
        * 刑法的使用效力
            * 空间效力
            * 时间效力
    * 犯罪论<<orange>>
        * 犯罪成立问题
            * 客观违法阶层
                * 客观要件
                    * 行为主体
                    * 危害行为
                    * 危害结果
                    * 因果关系
                * 客观（违法）阻却事由
                    * 正当防卫
                    * 紧急避险
                    * 被害人承诺
            * 主观责任阶层
                * 主观要件
                    * 犯罪故意
                    * 犯罪过失
                * 主观（责任）阻却事由
                    * 责任
                        * 责任年龄
                        * 责任能力
                    * 可能性
                        * 违法性认识可能性
                        * 期待可能性
        * 犯罪成立之后的问题
            * 犯罪的事件发展问题：犯罪形态（预备 → 中止 → 未遂 → 既遂）
            * 犯罪的空间分布问题：共同犯罪（正犯 → 共犯）
            * 犯罪的数量计算问题：罪数（一罪 → 数罪）
    * 刑罚论
        * 刑罚的体系
            * 主刑、附加刑、非刑罚处罚措施
        * 刑罚的裁量
            * 量刑情节、累犯、自首、立功、数罪并罚、缓刑
        * 刑罚的执行和消灭
            * 减刑、假释、时效

@endmindmap
