@startmindmap

!include ../style/mind-map-style.iuml

title 结果加重犯-法定性

* 结果加重犯-法定性
    * 过失心理<<green>>
        * 故意伤害
            * 致人死亡
        * 非法拘禁罪
            * 致人重伤、死亡
        * 暴力干涉婚姻自由罪
            * 致人死亡
        * 虐待罪致人死亡
            * 区分（不构成）<<orange>>
                * 侮辱罪
                * 诽谤罪
                * 遗弃罪
        * 抢夺罪（过失）
            * 致人重伤、死亡（司法解释的规定）
    * 故意或过失<<green>>
        * 抢劫罪
            * 致人重伤、死亡
        * 强奸罪
            * 致人重伤、死亡
            * 区分（不构成）<<orange>>
                * 强制猥亵罪<<orange>>
        * 拐卖妇女、儿童罪
            * 致人重伤、死亡
        * 放火罪
            * 致人重伤、死亡


@endmindmap