@startmindmap

!include ../style/mind-map-style.iuml

title 两阶层犯罪构成体系

* 两阶层犯罪构成体系
    * 客观违法阶层 <<green>>
        * 客观要件（违法事实）
            * 行为主体
            * 危害行为
            * 危害结果
            * 因果关系
        * 客观违法阻却事由
            * 正当防卫
                *_ 拿刀杀人，被反杀
            * 紧急避险
                *_ 着火，扔草堆
            * 被害人承诺等
                *_ 找人告自己贪污
    * 主观责任阶层 <<orange>>
        * 主观要件（能否谴责）
            * 犯罪故意（事实认识错误）
            * 犯罪过失（无罪过事件）
        * 主观责任阻却事由
            * 责任年龄（身体-年龄）
                *_ 狗蛋10岁
            * 责任能力（身体-能力）
                *_ 狗蛋不会游泳
            * 违法性认识可能行（意识-认知）
                *_ 询问法院，法院告诉不违法
            * 期待可能性（生存-生死）
                *_ 丈夫失踪，无法生存，再婚

@endmindmap