@startmindmap

!include ../style/mind-map-style.iuml

title 行为主体-单位

* 行为主体-单位
    * 单位犯罪的成立条件
        * 客观条件
        * 主体条件（重点） <<green>>
            * 主要判断一个问题：单位要构成单位犯罪，是否要求单位具有法人资格？
        * 主观条件（重点） <<green>>
            * 主要是两点
                * 第一，体现单位意志
                    * 故意犯罪，
                    * 过失犯罪，单位集体决策失误，工程重大安全事故罪
                * 第二，解开单位面纱（自然人把单位作为犯罪的马甲）
                    * 单位的主要目的：成立单位时的主要目的就是犯罪
                    * 单位的主要活动：成立单位的时候是合法的，之后把主营业务、主要活动都变成了犯罪
    * 单位犯罪的处罚
        * 处罚规则
            * 原则是双罚制，既罚单位，又罚个人
                * 个人，是指主管领导和其他直接责任人；他们都必须是参与了这个犯罪，才进行处罚
            * 例外单罚，只罚个人，不再罚单位了
                * 背后原理：单位犯罪，往往是几个领导在瞎搞；\n罚单位的话，就是罚单位的合法资产，缴纳罚金，\n就会侵犯其他股东、普通员工的利益，这不合理
        * 单位没了，怎么半？
            * 真没了，被撤销、注销、宣告破产，直接追究直接责任人的刑事责任
            * 假没了，被合并到一个新单位，追究原单位的单位犯罪
@endmindmap