@startmindmap

!include ../style/mind-map-style.iuml

title 大前提分类

* 大前提分类
    * <&star>记述的要素和规范的要素（最难，考的最多）<<green>>
        * 记述（描述事实）
            *_ 根据事实判断就能确定的要素，有客观标准\n例如，伪造、变造、护照、签证、毒品（毒品有客观标准）
        * 规范（价值评价）
            *_ 需要价值评价才能确定的要素，受判断者的价值影响\n同一件物品，有人认为是淫秽物品，有人认为是艺术品\n例如，猥亵、侮辱、淫秽物品，受人主观价值观的影响较大
        * 注意
            *_ “国家工作人员”，有价值评价的因素，也有事实判断的因素
    * 成文的要素和不成文的要素
    * 积极的要素和消极的要素
        * 积极：犯罪成立的要素（例如，徇私枉法罪中“司法工作人员”是积极的构成要件要素）
        * 消极：否定犯罪成立的要素（例如，“被勒索，没获利”，则不构成行贿罪）
    * 客观的要素和主观的要素
        * 客观：行为、结果、时间、地点
        * 主观：故意、过失、目的、动机

@endmindmap