@startmindmap

!include ../style/mind-map-style.iuml

title 行为主体-自然人

* 行为主体-自然人
    * 身份犯
        * 真正身份犯（定罪身份）
            *_ 只有“国家工作人员”才能构成贪污罪，“国家工作人员”就是一个定罪身份，“贪污罪”就是“真正的身份犯”
            * 考点
                * 定罪身份，必须在开始犯罪时就具备（时间）
                    *_ 在实施贪污前，就要有“国家工作人员”的身份
                    *_ 在犯罪过程中，才形成的某种身份、某种地位，那不构成定罪身份
                    *_ 组织卖淫罪的组织者，不算是一个定罪身份
                * 定罪身份，是仅针对实行犯要求的
                    *_ 构成贪污罪的实行犯，需要有国家工作人员的身份
                    *_ 构成贪污罪的帮助犯或者教唆犯等共犯，不需要国家工作人员的身份
        * 不真正身份犯（量刑身份）
            * 要构成诬告陷害罪，不需要“定罪身份”，犯罪主体是一般主体
            * 如果有一类人（“国家工作人员”）构成诬告陷害罪，那么在量刑上要从重处罚，那么“国家工作人员”就是“量刑身份”
            * 由此可以说“诬告陷害罪”，就是一个“不真正身份犯”
    * 国家工作人员
        * 范围
            * 国家工作人员 <<green>>
                * 国家机关工作人员 <<green>>
                    * 立法机关
                    * 司法工作人员 <<green>>
                    * 行政机关（执法机关）
                * 国有企业里某些人员
                * 国有事业单位里某些人员（考点） <<orange>>
                    * 公立大学、高校
                    * 公立医院
        * 判断标准
            * 错误标准（形式化标准）
                *_ 根据有无编制来认定，往往认为临时工不是国家工作人员
            * 正确标准（实质标准）
                * 是否从事公务（刑法93条）
                    * 判断公务标准
                        * 第一，事务具有“公共管理性”
                        * 第二，事务具有“行政职责性”
                    * 示例
                        *_ 事务关系到多数人或不特定人的利益；公立大学财务处会计属于国家工作人员（是）
                        *_ 仅与个别人或少数人相关的事务，不是公务；大学教授属于非国家工作人员，属于技术劳动（否）
                        *_ 临时切换；村干部协助政府从事公务时，属于国家工作人员（是）；从事村务，非公务时，不属于国家工作人员（否）
@endmindmap