@startmindmap

!include ../style/mind-map-style.iuml

title 行为主体-单位犯罪和自然人犯罪的关系

* 行为主体-单位犯罪和自然人犯罪的关系
    * 怎么区分单位犯罪和单位内部成员的个人犯罪？
        * 单位犯罪
            * 单位意志 --> 本单位利益
                *_ 全体人员，利益均沾，但不一定利益均分
                *_ 领导可能分的多，普通员工分的少
        * 个人犯罪
            * 单位意志 --> 成员个人利益（少数特定人）<<orange>>
                *_ 领导开会，领导几个人瓜分了公司的100万
            * 成员个人意志 --> 本单位利益（全体人员）<<orange>>
                *_ 狗蛋暗恋老板小芳，私自造假账逃税，为公司谋取利益
            * 成员个人意志 --> 成员个人利益（少数特定人）
    * 单位实施纯正的个人犯罪，应该怎么半？
        * 直接责任人
        * 如果单位实施一个纯正的自然人犯罪，那就定单位里面的直接责任人的个人犯罪

@endmindmap