@startmindmap

!include ../style/mind-map-style.iuml

title 定罪方法-三阶段推理

* 定罪方法-三阶段推理
    * 大前提
        * 法律规定（解释）
    * 小前提
        * 案件事实（认定）
    * 结论
        * 有罪无罪（推导或法律适用）
            *_ 根据小前提是否符合大前提，得出有罪或无罪的结论。

@endmindmap