@startmindmap

title 两阶层体系

* 两阶层体系
    *[#Orange] 客观
        * 违法阶层：客观要件
            * 行为主体
            * 危害行为
            * 危害结果
            * 因果关系
        * 违法阻却事由
            * 正当防卫
            * 紧急避险
            * 被害人承诺等
    * 主观
        * 责任阶层：主观要件
            * 犯罪故意（事实认识错误）
            * 犯罪过失（无罪过事件）
        * 责任阻却事由
            * 责任年龄
            * 责任能力
            * 违法性认识可能行
            * 期待可能性

@endmindmap