<style>
mindmapDiagram {
  .blue {
    BackgroundColor lightblue
  }
  .darkred {
    BackgroundColor darkred
  }
  .green {
    BackgroundColor lightgreen
  }
  .grey {
    BackgroundColor lightgrey
  }
  .orange {
    BackgroundColor orange
  }
  .purple {
    BackgroundColor purple
  }
  .red {
    BackgroundColor red
  }
  .rose {
    BackgroundColor #FFBBCC
  }
  .yellow {
    BackgroundColor yellow
  }
}
</style>